[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
num-bigint = "0.4.4"
num-rational = "0.4.1"
proptest = "1.3.1"
