[package]
name = "composeable-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.0"
num-traits = "0.2.17"
raw-cpuid = "11.0.1"
